service_label = 'python-service'

load_dynamic("../go-service/Tiltfile")

docker_build(
    service_label,
    '.',
    live_update=[
        sync('./main.py', '/app/main.py'),
        run('cd /app && pip install -r requirements.txt',
            trigger='./requirements.txt')
    ]
)

k8s_yaml(kustomize('./kubernetes'))
k8s_resource(service_label, port_forwards=8000, labels=service_label)
