kind: PersistentVolume
apiVersion: v1
metadata:
  name: cockpit-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/psql/java-service-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi