service_label="react-frontend"

load_dynamic("../python-service/Tiltfile")
load_dynamic("../go-service/Tiltfile")
load_dynamic("../java-service/Tiltfile")

local_resource(
    name='react-frontend',
    serve_cmd='npm start',
    readiness_probe=probe(
      period_secs=15,
      http_get=http_get_action(port=3000)
    ),
    labels=[service_label]
)